org: lovendatj
service: aws-file-upload
frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.9
  profile: lovendatj
  lambdaHashingVersion: 20201221
  iam:
    role:
      name: role
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 'dynamodb:*'
        - Effect: 'Allow'
          Resource: '*'
          Action: 's3:*'
          
#  TODO Add Function for trigger on upload
# functions:
#   readingList:
#     handler: CreateReadingList.reading_list

resources:
  Resources:
    ReadingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ReadingTable
        AttributeDefinitions:
          - AttributeName: textId
            AttributeType: S
        KeySchema:
          - AttributeName: textId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST