org: lovendatj
service: aws-file-upload
frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.9
  profile: lovendatj
  lambdaHashingVersion: 20201221
  iam:
    role:
      name: role
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 'dynamodb:*'
        - Effect: 'Allow'
          Resource: '*'
          Action: 's3:*'

resources:
  Resources:
    TableAsset:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: {TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    
    S3Assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-assets